# Generated by Django 5.2.4 on 2025-08-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_cinema_image_alter_hall_map_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gallery',
            field=models.ManyToManyField(related_name='movies', to='cinema.image'),
        ),
    ]
