# Generated by Django 5.2.4 on 2025-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hall_cinema_alter_movie_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
