# Generated by Django 5.2.4 on 2025-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_cinema_slug_alter_seoblock_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='movies', to='cinema.image'),
        ),
    ]
