# Generated by Django 5.2.4 on 2025-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='cinemas', to='cinema.image'),
        ),
        migrations.AddField(
            model_name='hall',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='halls', to='cinema.image'),
        ),
    ]
