# Generated by Django 5.2.4 on 2025-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_cinema_gallery_hall_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
