# Generated by Django 5.2.4 on 2025-08-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_hall_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
        ),
    ]
