# Generated by Django 5.2.5 on 2025-08-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('news', 'Новость'), ('promo', 'Акция')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_news/')),
                ('text', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gallery', models.ManyToManyField(blank=True, related_name='promo_news', to='cinema.image')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.seoblock')),
            ],
        ),
    ]
