# Generated by Django 5.2.5 on 2025-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promonews',
            name='link_on_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
