# Generated by Django 5.2.4 on 2025-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hall_cinema_alter_movie_gallery'),
        ('promotion', '0002_alter_promonews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promonews',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='promo_news', to='cinema.image'),
        ),
    ]
