# Generated by Django 5.2.5 on 2025-08-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('is_background', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BgBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_image_background', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='background_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uk', 'Українська')], max_length=2)),
                ('cinema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(max_length=20)),
                ('seo_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uk', 'Українська')], max_length=2)),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='MainUpperBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('rotation_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ManyToManyField(related_name='main_upper_banners', to='dashboard.bannerimage')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('rotation_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ManyToManyField(related_name='news_promo_banners', to='dashboard.bannerimage')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static_pages/')),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uk', 'Українська')], default='ru', max_length=2)),
                ('gallery', models.ManyToManyField(blank=True, related_name='pages', to='cinema.image')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock')),
            ],
        ),
    ]
