# Generated by Django 5.2.4 on 2025-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_bannerimage_image_alter_bgbanner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainupperbanner',
            name='image',
            field=models.ManyToManyField(related_name='main_upper_banners', to='dashboard.bannerimage'),
        ),
        migrations.AlterField(
            model_name='newspromobanner',
            name='image',
            field=models.ManyToManyField(related_name='news_promo_banners', to='dashboard.bannerimage'),
        ),
    ]
