# Generated by Django 5.2.4 on 2025-08-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hall_cinema_alter_movie_gallery'),
        ('dashboard', '0003_page_is_active_alter_mainupperbanner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='pages', to='cinema.image'),
        ),
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uk', 'Українська')], default='ru', max_length=2),
        ),
    ]
