# Generated by Django 5.2.4 on 2025-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_page_gallery_page_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainupperbanner',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspromobanner',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
