# Generated by Django 5.2.4 on 2025-08-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_mainupperbanner_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainupperbanner',
            name='rotation_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspromobanner',
            name='rotation_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
